import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

// const inter = Inter({
//   subsets: ["latin"],
// });

const geist = Geist({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Open Collective Features",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.className} antialiased`}>{children}</body>
    </html>
  );
}
